[package]
name = "specmc-base"
version = "0.1.11"
authors = ["TheAIguy_"]
edition = "2021"
description = "A library with common code for parsing Minecraft specification."
repository = "https://github.com/SpecMC/Base"
license = "MIT"

[dependencies]
thiserror = "1.0.61"
strtoint = "0.1.0"
