[package]
name = "specmc-base"
version = "0.1.0"
edition = "2021"
description = "A library with common code for parsing Minecraft specification files."
license = "MIT"

[dependencies]
thiserror = "1.0.61"
strtoint = "0.1.0"
